env:
  global:
    - CC_TEST_REPORTER_ID=85ab071861c7d30ea718846ec262a1c2b3c9d213204d6a4a1db8428843de6905
language: python
python:
  - "3.8"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  python amcom/manage.py test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT