language: python
python:
  - "3.8"
addons:
  postgresql: "10.10"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coverage
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  coverage run amcom/manage.py test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT